package apperr

import (
	"errors"
)

var (
	ErrAistudioNotFound                = errors.New("aistudio not found")
	ErrAIModelNode404                  = errors.New("error while fetching ai model node")
	ErrAIModelConn                     = errors.New("error while fetching ai model connection")
	ErrGetAIModelNetParams             = errors.New("error while fetching ai model net params")
	ErrAIModelNode403                  = errors.New("error while fetching ai model node")
	ErrAIModelManagerAction404         = errors.New("error while fetching ai model manager action")
	ErrAIPrompt404                     = errors.New("error while fetching ai prompt")
	ErrAIGuardrail404                  = errors.New("error while fetching ai guardrail")
	ErrAIStudioChat404                 = errors.New("error while fetching ai studio chat")
	ErrAIStudioChat400                 = errors.New("error while creating ai studio chat")
	ErrDifferentChatRequested          = errors.New("error while selecting chat, different chat requested.Please use the current chat or create a new chat")
	ErrInvalidAction                   = errors.New("invalid action for this request")
	ErrInvalidAIModelNodeRequestSpec   = errors.New("invalid AI model node request spec")
	ErrInvalidAIModelNodeRequested     = errors.New("invalid AI model node requested")
	ErrSavingAIModelNode               = errors.New("error while saving AI model node metadata in elasticsearch")
	ErrSettingAIModelNodeCredentials   = errors.New("error while setting AI model node credentials")
	ErrCrawlingAIModels                = errors.New("error while crawling AI models")
	ErrAIModelManagerPromptTemplate404 = errors.New("AI model manager prompt template not found")
	ErrSavingAIPrompt                  = errors.New("error while saving AI model prompt to datastore")
	ErrInvalidAIPromptRequestSpec      = errors.New("invalid AI model prompt request spec")
	ErrAIPromptNotEditable             = errors.New("AI prompt is not editable")
	ErrUpdatingAIModelNode             = errors.New("error while updating AI model node metadata in elasticsearch")
	ErrPrompt403                       = errors.New("error while validating user access")
	ErrAIAgent404                      = errors.New("AI agent not found")
	ErrAIAgentCreate500                = errors.New("error while creating AI agent")
	ErrAIAgentNotEditable              = errors.New("AI agent is not editable")
	ErrAIAgentPatch400                 = errors.New("error while patching AI agent")
	InvalidDataProductParam            = errors.New("invalid data product params")
	InvalidContentFormatParam          = errors.New("invalid content format params")
	ErrInvalidAIModels                 = errors.New("error while getting AI model list from datastore")
	ErrInvalidAgentChainParams         = errors.New("invalid agent chain parameters")
	ErrInvalidAgentType                = errors.New("invalid agent type")
	ErrFileDataNotFound                = errors.New("error while getting file data")
	ErrInvalidDataFormat               = errors.New("invalid data format")
	ErrAIGuardrailNotEditable          = errors.New("AI guardrail is not editable")
	ErrAIGuardrailPatch400             = errors.New("error while patching AI guardrail")
	ErrAIGuardrailCreate400            = errors.New("error while creating AI guardrail")
	ErrAIGuardrail403                  = errors.New("error while validating user access to AI guardrail")
	ErrMissingResource                 = errors.New("missing resource")
	ErrResourceNotActive               = errors.New("resource not active")
	ErrInvalidAIStudioChatRequested    = errors.New("invalid AI studio chat requested")
	ErrCreatingAIStudioChat            = errors.New("error while creating AI studio chat")
	ErrArchiveFabricChat               = errors.New("error while archiving AI studio chat")
	ErrAIStudio403                     = errors.New("error while validating user access to AI studio chat")
	ErrInvalidAIResponseFormat         = errors.New("invalid AI response format")
	ErrInvalidContentFormatParams      = errors.New("invalid content format params")
	ErrVapusAgentVersionSpec           = errors.New("error while fetching vapus agent version spec")
	ErrVapusAgentVersion404            = errors.New("error while fetching vapus agent version")
	ErrVapusAgentVersion403            = errors.New("error while validating user access to vapus agent version")
	ErrFaricSummaryGenerate            = errors.New("error while generating fabric summary")
	ErrFaricSummarySave                = errors.New("error while saving fabric summary")
	ErrInvalidOrMissingPodelAPIKey     = errors.New("invalid model API key, please check the API key and try again")
)
