package apperr

import "errors"

var (
	ErrDataOwnerExecutionFailed            = errors.New("error while executing data observerability query")
	ErrDataVisualizationFailed             = errors.New("error while visualizing data")
	ErrCommunicationActionFailed           = errors.New("error while performing communication action")
	ErrDataAnalysisFailed                  = errors.New("error while analyzing data")
	ErrDataproductSearchFailed             = errors.New("error while searching data products")
	ErrDataLoadingFailed                   = errors.New("error while loading data")
	ErrInvalidVapusAgent                   = errors.New("invalid nabhik agent")
	ErrSavingVapusAgentUpdateRun           = errors.New("error while saving nabhik agent update run")
	ErrSavingVapusAgentLog                 = errors.New("error while saving nabhik agent log")
	ErrAgentInputAnalysisFailed            = errors.New("error while analyzing agent input")
	ErrNabhikSuggestionGenerationFailed    = errors.New("error while generating nabhik suggestion")
	ErrChatNextRouteFailed                 = errors.New("error while routing chat to next agent")
	ErrInvalidNextAction                   = errors.New("invalid next action")
	ErrInvalidNabhikTaskRequested          = errors.New("invalid nabhik task requested")
	ErrInvalidNabhikTasktRequested         = errors.New("invalid nabhik task requested")
	ErrCreatingNabhikTask                  = errors.New("error while creating nabhik task")
	ErrNabhikTaskOwner403                  = errors.New("error while creating nabhik task")
	ErrUpdatingNabhikTask                  = errors.New("error while updating nabhik task")
	ErrAgentWorkFailed                     = errors.New("error while performing agent work")
	ErrNabhikChatProcessingFailed          = errors.New("error while processing nabhik chat")
	ErrMarshallingMessageSummary           = errors.New("error while marshalling message summary")
	ErrNabhikPlanningFailed                = errors.New("error while planning nabhik")
	ErrCreatingChatDirectory               = errors.New("error while creating chat directory")
	ErrOpeningChatDirectory                = errors.New("error while opening chat directory")
	ErrGettingCurrentWorkingDirectory      = errors.New("error while getting current working directory")
	ErrCheckingChatDirectory               = errors.New("error while checking chat directory")
	ErrDataAnalysisSummarizationFailed     = errors.New("error while summarizing data analysis")
	ErrInvalidNabhikChat                   = errors.New("error while processing the query, invalid nabhik chat")
	ErrCreatingNabhikChat                  = errors.New("error while processing the query, error while creating nabhik chat")
	ErrEndingNabhikChat                    = errors.New("error while processing the query, error while ending nabhik chat")
	ErrNabhikChatMessageExhausted          = errors.New("error while processing the query, nabhik chat message limit exhausted. Create a new chat thread.")
	ErrNabhikChatAnalysisFailed            = errors.New("error while processing the query, nabhik chat analysis failed")
	ErrSavingNabhikChat                    = errors.New("error while processing the query, error while saving nabhik chat")
	ErrInvalidNabhikManagerRequest         = errors.New("error while processing the query, invalid nabhik manager request")
	ErrInvalidNabhikChatRequested          = errors.New("error while processing the query, invalid nabhik chat requested")
	ErrNabhikDataQueryfailed               = errors.New("error while processing the query, nabhik data query failed")
	ErrInvalidNabhikChat404                = errors.New("error while processing the query, invalid nabhik chat 404")
	ErrInvalidNabhikChat403                = errors.New("error while processing the query, invalid nabhik chat 403")
	ErrInvalidNabhikFileRequested          = errors.New("error while processing the query, invalid nabhik file requested")
	ErrInvalidNabhikRole                   = errors.New("error while processing the query, invalid nabhik role")
	ErrNabhikChatInitFailed                = errors.New("error while initializing nabhik chat")
	ErrChartBuildingFailed                 = errors.New("error while building chart")
	ErrCodeGenerationFailed                = errors.New("error while generating code")
	ErrTaskManagementFailed                = errors.New("error while managing task")
	ErrTaskBuilderInputUnmarshallingFailed = errors.New("error while unmarshalling task builder input")
	ErrTaskBuilderInputMarshallingFailed   = errors.New("error while marshalling task builder input")
	ErrCreatingTaskLead                    = errors.New("error while creating task lead")
	ErrTaskAssetMissing                    = errors.New("error while processing the query, task asset missing")
	ErrHsnAssetLoadingFailed               = errors.New("error while loading hsn asset")
	ErrHsnAssetDataLoadingFailed           = errors.New("error while loading hsn asset data")
	ErrHsnAssetFieldDetertionLoadingFailed = errors.New("error while loading hsn asset field detection")
	ErrHSNAndGSTValidationFailed           = errors.New("error while validating hsn and gst data")
)
